name: Build, Test, Package

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.csproj'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]

jobs:
  windows-test:
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Sdk
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            8.x
    - name: Test .NET Standard
      run: dotnet test -v normal -f net8.0 --logger "console;verbosity=detailed"
    - name: Test .NET FW 4.8
      run: dotnet test -v normal -f net48 --logger "console;verbosity=detailed"
      
  upload-packages:
    needs: [windows-test] 
    if: success()
    runs-on: windows-2022
    strategy:
      matrix:
        project: [ 'Nuve.DataStore', 'Nuve.DataStore.Redis','Nuve.DataStore.Serializer.JsonNet','Nuve.DataStore.Serializer.Ceras' ]
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Publish Nuget Package
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/${{ matrix.project }}/${{ matrix.project }}.csproj
        INCLUDE_SYMBOLS: true
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_FORMAT: v*
